platform :ios, '10.0'

target 'ReactNativeVideoCompressExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeGroovecat
  pod 'GoogleMobileVision/FaceDetector'
  pod 'GoogleMobileVision/MVDataOutput'

end

